####################################################################
######################### STATEFUL BACKEND #########################
####################################################################

# Service for Stateful containers, listening on port 3002
apiVersion: v1
kind: Service
metadata:
  name: api-stateful
spec:
  type: LoadBalancer
  selector:
    app: stateful
  ports:
  - port: 80
    name: http
    targetPort: http
---
# Deployment for pocbackend containers, listening on port 3000
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateful
  template:
    metadata:
      labels:
        app: stateful
    spec:
       containers:
       - name: windows-poc
         image: pock8sregistry.azurecr.io/windows-poc:1.0
         imagePullPolicy: IfNotPresent
         ports:
          - name: http
            containerPort: 3000
 
#############################################################
########### ISTIO PROXY FOR API-STATEFUL SERVICE ############
#############################################################
---
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#     name: sticky-svc
# spec:
#     host: api-stateful
#     trafficPolicy:
#      loadBalancer:
#        consistentHash:
#          httpCookie:
#            name: session-id
#            ttl: 20000s
