apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksping
spec:
  selector:
      matchLabels:
        app: aksping
  replicas: 3
  template:
      metadata:
        labels:
            app: aksping
      spec:
        containers:
        - name: aksping
          image: pock8sregistry.azurecr.io/aksping:1.0
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            httpGet:
              port: 8080
              path: /
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
        imagePullSecrets:
        - name: poc-k8s-registry-pull-secret