apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksping
spec:
  selector:
      matchLabels:
        app: aksping
  replicas: 3
  template:
      metadata:
        labels:
            app: aksping
      spec:
        containers:
        - name: aksping
          image: pockK8sRegistry.azurecr.io/aksping:v1
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            httpGet:
              port: 8080
              path: /
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
