#Copy paste in Azure CLI
#This uses the login and id generated by the script create-acr-principal, stored in service-principal-id.md

kubectl create secret docker-registry poc-k8s-registry-pull-secret \
    --docker-server=pock8sregistry.azurecr.io \
    --docker-username=ec4601ce-1d01-480c-89e5-e72568ab7330 \
    --docker-password=6_NFpzLDjJFZwEd~IST.56oL1S5Z.VEbng