####################################################################
######################### STATEFUL BACKEND #########################
####################################################################

# Service for Stateful containers, listening on port 3002
apiVersion: v1
kind: Service
metadata:
  name: win-svc
spec:
  type: NodePort
  selector:
    app: wintest
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30000
---
# Deployment for pocbackend containers, listening on port 3000
apiVersion: apps/v1
kind: Deployment
metadata:
  name: win-test-with-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wintest
  template:
    metadata:
      labels:
        app: wintest
    spec:
       containers:
       - name: windows-poc
         image: windows-poc:1.0
         ports:
          - name: http
            containerPort: 3000
         volumeMounts:
          - mountPath : /log
            name: log-volume
          - mountPath : /config
            name: config-volume
       volumes:
       - name: log-volume
         hostPath:           
           path: '/host_mnt/d/dev/poc-k8s/log'
           type: Directory
       - name: config-volume
         hostPath:           
           path: '/host_mnt/d/dev/poc-k8s/config/local'           
           type: Directory
            