####################################################################
######################### STATEFUL BACKEND #########################
####################################################################

# Service for Stateful containers, listening on port 3002
apiVersion: v1
kind: Service
metadata:
  name: linuxpg-svc
spec:
  type: NodePort
  selector:
    app: linuxpg
  ports:
  - protocol: TCP
    targetPort: 3000
    port: 3000
    nodePort: 30000
---
# Deployment for pocbackend containers, listening on port 3000
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linuxpg-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linuxpg
  template:
    metadata:
      labels:
        app: linuxpg
    spec:  
       containers:
       - name: linux-pg
         image: linux-pg:1.0
         ports:
          - name: http
            containerPort: 3000
         volumeMounts:
           - mountPath : /config
             name: config-volume
       volumes:
       - name: config-volume
         hostPath:           
           path: '/host_mnt/D/dev/poc-k8s/config/local'           
           type: Directory