#############################################################
######################### FRONT END #########################

apiVersion: v1
kind: Service
metadata:
  name: front-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: front
    tier: webserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3500
---
# deployment of the container pocfrontend listening to port 3500
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
      tier: webserver
  template:
    metadata:
      labels:
        app: front
        tier: webserver
    spec:
      imagePullSecrets:
      - name: poc-k8s-registry-pull-secret
      containers:
      - name: pocfrontend
        image: pock8sregistry.azurecr.io/pocfrontend:1.0               
        ports:
           - name: http-front
             containerPort: 3500      
        volumeMounts:
           - mountPath : /log
             name: log-volume
           - mountPath : /config
             name: config-volume
      volumes:
      - name: log-volume
        azureFile:
          shareName: pock8sshare
          secretName: pock8s-share-secret
          readOnly: false
      - name: config-volume
        azureFile:
          shareName: pock8s-share
          secretName: pock8s-share-secret
          readOnly: false

