####################################################################
######################### STATEFUL BACKEND #########################
####################################################################

# Service for Stateful containers, listening on port 3002
apiVersion: v1
kind: Service
metadata:
  name: api-stateful
spec:
  selector:
    app: stateful
    tier: appserver
  ports:
  - port: 3002
    name: http-stful
    targetPort: http-stateful
---
# Deployment for pocbackend containers, listening on port 3000
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stateful
      tier: appserver
  template:
    metadata:
      labels:
        app: stateful
        tier: appserver
    spec:
       imagePullSecrets:
       - name: poc-k8s-registry-pull-secret
       containers:
       - name: pocbackend
         image: pock8sregistry.azurecr.io/pocbackend:1.0
         ports:
          - name: http-stateful
            containerPort: 3000
         volumeMounts:
          - mountPath : /log
            name: log-volume
          - mountPath : /config
            name: config-volume
       - name: localsessionmanager
         image: localsessionmanager:1.0
         ports:
          - name: http-lmgt
            containerPort: 3400
         env:
          - name: MY_NODE_NAME
            valueFrom:
             fieldRef:
              fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name         
         volumeMounts:
          - mountPath : /log
            name: log-volume
          - mountPath : /config
            name: config-volume
       volumes:
        - name: log-volume
          azureFile:
           shareName: pock8sshare
           secretName: pock8s-share-secret
           readOnly: false
        - name: config-volume
          azureFile:
           shareName: pock8sshare
           secretName: pock8s-share-secret
           readOnly: false

#############################################################
########### ISTIO PROXY FOR API-STATEFUL SERVICE ############
#############################################################
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#     name: sticky-svc
# spec:
#     host: api-stateful
#     trafficPolicy:
#      loadBalancer:
#        consistentHash:
#          httpCookie:
#            name: session-id
#            ttl: 20000s
