
#####################################################################
######################### STATELESS BACKEND #########################

# Service for Stateless containers, listening on port 3000
apiVersion: v1
kind: Service
metadata:
  name: api-stateless
spec:
  selector:
    app: stateless
    tier: appserver
  ports:
  - port: 3001
    name: http-stless
    targetPort: http-stateless
---
# Deployment for pocbackend containers, listening on port 3000
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateless
      tier: appserver
  template:
    metadata:
      labels:
        app: stateless
        tier: appserver
    spec:
      imagePullSecrets:
      - name: poc-k8s-registry-pull-secret
      containers:
      - name: pocbackend
        image: pock8sregistry.azurecr.io/pocbackend:1.0        
        ports:
           - name: http-stateless
             containerPort: 3000        
        volumeMounts:
           - mountPath : /log
             name: log-volume
           - mountPath : /config
             name: config-volume
      volumes:
       - name: log-volume
         azureFile:
           shareName: pock8sshare
           secretName: pock8s-share-secret
           readOnly: false
       - name: config-volume
         azureFile:
           shareName: pock8sshare
           secretName: pock8s-share-secret
           readOnly: false

           