####################################################################
######################### STATEFUL BACKEND #########################
####################################################################

# Service for Stateful containers, listening on port 3002
apiVersion: v1
kind: Service
metadata:
  name: linuxpg-svc
spec:
  type: LoadBalancer
  selector:
    app: linuxpg
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
# Deployment for pocbackend containers, listening on port 3000
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linuxpg-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linuxpg
  template:
    metadata:
      labels:
        app: linuxpg
    spec:  
       imagePullSecrets:
       - name: poc-k8s-registry-pull-secret
       containers:
       - name: linux-pg
         imagePullPolicy: Always
         image: pock8sregistry.azurecr.io/linux-pg:1.0
         ports:
          - name: http
            containerPort: 3000
         volumeMounts:
           - mountPath : /log
             name: log-volume
           - mountPath : /config
             name: config-volume
       volumes:
       - name: log-volume
         azureFile:
          shareName: pock8sshare
          secretName: pock8s-share-secret
          readOnly: false
       - name: config-volume
         azureFile:
          shareName: pock8sshare
          secretName: pock8s-share-secret
          readOnly: false
